name: Actualizar Precios
on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch:      # Botón manual

jobs:
  build:
    runs-on: ubuntu-latest
    
    # ESTO ES LO NUEVO: Fuerza los permisos de escritura desde el código
    permissions:
      contents: write
      
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install yfinance pandas

      - name: Ejecutar script
        run: python cotizac.py

      - name: Diagnóstico (Ver si se creó el archivo)
        run: |
          ls -l  # Esto mostrará en la consola si index.html existe

      - name: Guardar y Publicar
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add index.html
          git commit -m "Actualizar precios" || echo "Sin cambios para subir"
          git push
